### PR TITLE
Add the ability to handle saving log to file

### PR DESCRIPTION
**Pull request by damianpolak**

### CODE REVIEW

**Review by chrisharrison — COMMENTED** [review]
How about adding the ability to add a logger that uses the PSR-3 logging interface?
https://github.com/php-fig/log/tree/master/Psr/Log

Then users can attach any logging implementation they want.

**Comment by nekudo** [comment]
https://github.com/bloatless/php-websocket/compare/feature/logger

I added the possibility to add PSR-3 loggers in this branch. Would be nice to get some feedback.

**Comment by chrisharrison** [comment]
You can use composer to add logging rather than copy and pasting the code in.

i.e. run `composer require psr/log`

Also, you don't need to loop through a set of loggers. What you can do is add the ability to add a single logger to the server that implements the PSR-3 interface.

If in your particular implementation you wanted to have multiple loggers, you could set something like a 'composite logger' on the websocket server.

i.e.
```
final class CompositeLogger implements LoggerInterface
{
    /**
     * @var LoggerInterface[]
     */
    private $loggers;
    
    public function __construct(array $loggers)
    {
        $this->loggers = $loggers;
    }

    public function log($level, $message, array $context = array())
    {
        foreach ($this->loggers as $logger) {
            $logger->log($level, $message, $context);
        }
    }
    ...
}
```

(or something like that).

This way you are keeping the logging concern completely separate from the websocket server. All it knows is it accepts something that implements the standardised logger interface and sends messages to it.

The composite logger would be something you would do at the project level. Not part of this websocket package.

**Comment by nekudo** [comment]
Thanks for your feedback.

Just FYI: Not using composer was "by design" as composer introduces itself as a dependency and a project can not be used/installed as soon as there is problem with the whole ecosystem. But as this project is not indented to be used in production anyways I decided to go for it ;)

**Comment by nekudo** [comment]
In the next release it will be possible to set any PSR-3 compatible logger. (Can already be tested using the master branch)

**Pull request closed without merging**
